# Generated by Django 5.1.4 on 2025-04-30 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('lottery_id', models.AutoField(primary_key=True, serialize=False)),
                ('lottery_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('winner_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
