# Generated by Django 5.1.4 on 2025-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0004_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='is_Deployed',
            field=models.BooleanField(default=False),
        ),
    ]
