# Generated by Django 5.1.4 on 2025-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0006_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='solidity',
            fields=[
                ('solidity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ABI', models.TextField()),
                ('Byte_code', models.TextField()),
                ('Code', models.TextField()),
            ],
        ),
    ]
