# Generated by Django 5.2 on 2025-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0007_solidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='lottery_images/'),
        ),
    ]
