# Generated by Django 5.2 on 2025-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0008_lottery_discription_lottery_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='static/lottery_images/'),
        ),
    ]
