# Generated by Django 5.2 on 2025-05-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0009_alter_lottery_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='discription',
            new_name='description',
        ),
    ]
